// Scans the prerendered SvelteKit build for inline <script> tags and writes an
// nginx include (nginx/csp.conf) that sets the Content-Security-Policy header
// with those scripts' sha256 hashes, so script-src needs no 'unsafe-inline'.
// Run by build.sh after the frontend build; the hashes change with every build.
//
// Usage: node scripts/csp-hashes.mjs <build-dir> <output-file>
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const [buildDir, outPath] = process.argv.slice(2);
if (!buildDir || !outPath) {
	console.error('usage: csp-hashes.mjs <build-dir> <output-file>');
	process.exit(1);
}

const htmlFiles = readdirSync(buildDir, { recursive: true })
	.filter((f) => f.endsWith('.html'))
	.map((f) => join(buildDir, f));

const scriptTag = /<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g;
const hashes = new Set();
for (const file of htmlFiles) {
	for (const [, body] of readFileSync(file, 'utf8').matchAll(scriptTag)) {
		if (body.trim() === '') continue;
		hashes.add(`'sha256-${createHash('sha256').update(body).digest('base64')}'`);
	}
}
if (hashes.size === 0) {
	console.error(`no inline scripts found in ${buildDir}; refusing to write an empty script-src`);
	process.exit(1);
}

const directives = [
	"default-src 'self'",
	`script-src 'self' ${[...hashes].sort().join(' ')}`,
	// SvelteKit's client runtime creates a visually-hidden #svelte-announcer div
	// (screen-reader route-change announcements) with a hardcoded inline style
	// attribute. It never appears in the prerendered HTML (only after hydration),
	// so it can't be hashed above. The value is fixed by SvelteKit's source, not
	// user content, so it's pinned by hash instead of falling back to
	// unsafe-inline. 'unsafe-hashes' is required for a hash to match an attribute
	// rather than a <style> block. Re-verify this hash after a SvelteKit upgrade
	// (see internal/kit/src/core/sync/write_root.js).
	"style-src 'self' 'unsafe-hashes' 'sha256-S8qMpvofolR8Mpjy4kQvEm7m1q8clzU4dfDH0AmvZjo='",
	"img-src 'self' data:",
	"font-src 'self'",
	"connect-src 'self'",
	"form-action 'self'",
	"frame-ancestors 'none'",
	"base-uri 'self'",
	"object-src 'none'"
];

writeFileSync(
	outPath,
	`# Generated by scripts/csp-hashes.mjs -- do not edit.\nadd_header Content-Security-Policy "${directives.join('; ')}" always;\n`
);
console.log(`wrote ${hashes.size} script hashes from ${htmlFiles.length} html files to ${outPath}`);
